name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    env:
      CURRENT_BRANCH: main
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@amraneze'
      - name: Install dependencies
        run: yarn install
      - name: Lint the project
        run: yarn lint
      - name: Build the project
        run: yarn build
      - name: Upload a build artifact to main
        if: ${{ contains(github.event.head_commit.message, 'bump version') }}
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git add .
          git commit -m 'ci: publish osm-autocomplete'
          git push
      - run: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}